a=input('Digite algo: ')

print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É número(s)? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alphanumerico? ', a.isalnum())
print('Está em maiúsculas? ', a.isupper())
print('Está em minusculas? ', a.islower())
print('Está capitalizado? ', a.istitle())