a = int(input('Digite um número: '))

print("-" * 12)
print('0  x {:2} = {}'.format(a,a*0))
print('1  x {:2} = {}'.format(a,a*1))
print('2  x {:2} = {}'.format(a,a*2))
print('3  x {:2} = {}'.format(a,a*3))
print('4  x {:2} = {}'.format(a,a*4))
print('5  x {:2} = {}'.format(a,a*5))
print('6  x {:2} = {}'.format(a,a*6))
print('7  x {:2} = {}'.format(a,a*7))
print('8  x {:2} = {}'.format(a,a*8))
print('9  x {:2} = {}'.format(a,a*9))
print('10 x {:2} = {}'.format(a,a*10))
print("-" * 12)
